#####################
### Starship.toml ###
#####################

add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$fill\
$memory_usage\
$line_break\
$sudo\
$character """

[hostname]
ssh_only = false
disabled = false
# aliases = {
    # any aliases that we may want to set (ssh)    
# }

[username]
show_always = true
style_root = 'bold red'
style_user = 'bold blue'
format = '[$user]($style)[@](bold white)'

[character]
format = '$symbol '
success_symbol = '[\$](bold white)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[:](bold white)'
vimcmd_replace_one_symbol = '[:](bold white)'
vimcmd_replace_symbol = '[:](bold white)'
vimcmd_visual_symbol = '[:](bold white)'

[memory_usage]
format = '$symbol [${ram_pct}( | ${swap_pct})]($style) '
style = 'bold dimmed red'
disabled = false
threshold = 75
symbol = ' '
